### ISSUE TITLE
Register BOP (or other) biomes from RTG

### ISSUE THREAD

**Issue by topisani** [Team-RTG/1.9-Realistic-Terrain-Generation#15]
Basically this is the way to get rid of BiomeTweaker or CC as a dependency. If done right it would not require the BOP devs to do anything

**Comment by whichonespink44** [comment]
As long as RTG doesn't add any new biomes, or override biomes in such a way as to cause incompatibility issues with other mods, then I think this is something we should explore further.

**Comment by topisani** [comment]
Nope, it will just add the BOP biomes to the biome array if it's not done by something else.

**Comment by Zeno410** [comment]
Doesn't work. The biomes are already "registered" with RTG and in the biome array - RTG looks for BoP in the mod list. The problem is that the biomes don't appear in the world, because the vanilla layout doesn't place them (obviously). The simplest fix, if you're only looking at BoP for now, is for BoP to provide its genlayer stack for RTG worlds.

**Comment by topisani** [comment]
Im talking to the BOP guys, the only way to do this, at least without Kdots Biome system, is somehow stealing their genlayers like zeno said.

**Comment by Zeno410** [comment]
We have to steal? They won't give them willingly?

**Comment by topisani** [comment]
thats just the way i talk man! im waiting for adubz to come online though :D

**Comment by topisani** [comment]
in theory i have done this, the new setup #35 uses the BOP biome layout if BOP is installed. Its pretty much untestable though, since BOP needs to update

**Comment by topisani** [comment]
#35 is confirmed working! :D
