### ISSUE TITLE
Do we need biome repair?

### ISSUE THREAD

**Issue by topisani** [Team-RTG/1.9-Realistic-Terrain-Generation#85]
If terrain features turn out as i want them to, we can set the biome for lakes and rivers directly (since at least the lakes would be terrain features, if i could get away with it rivers will be too). What else does biome repair do? the thing is, its very hacky and doesnt allways work perfectly, so personally id like to find a way to place the correct biome earlier on. what parts of BiomeRepair exist, and what parts are absolutely necessary if we can solve the lake and possibly river issues with terrainFeatures?

**Comment by Zeno410** [comment]
Biome Repair is primarily for beach and coast issues. Because of smoothing, ocean biome territory can end up above water and land biomes below, and that has to be fixed. It's just a convenient place to set river biomes; it actually doesn't "repair" them; it runs much less complex code for that. It actually doesn't repair lakes, except sometimes when they're near ocean or rivers, and that's a side effect, not intentional.

**Comment by topisani** [comment]
aright, and that side effect can be killed this way :+1:
